### ISSUE TITLE
Getting KeyError: 'status' while trying to connect to OBS studio

### ISSUE THREAD

**Issue by Tirumala7** [Elektordi/obs-websocket-py#81] opened 2023-02-06 10:29 UTC
when we call ws.connect() function i am getting below issue
`INFO:obswebsocket.core:Connecting...
INFO:obswebsocket.core:Connected!
Traceback (most recent call last):
  File "C:\Users\Projects\OBSStudio\scripts\obsEvents.py", line 27, in <module>
    ws.connect()
  File "C:\Users\Projects\OBSStudio\scripts\venv\lib\site-packages\obswebsocket\core.py", line 70, in connect
    self._auth(self.password)
  File "C:\Users\Projects\OBSStudio\scripts\venv\lib\site-packages\obswebsocket\core.py", line 116, in _auth
    if result['status'] != 'ok':
KeyError: 'status'`

**Comment by iarspider** [comment] 2023-02-06 10:32
This packages is not (yet) compatible with obs-websocket 5.x (the one that is built into OBS v28+). You need to download and install  obs-websocket 4.9.1-compat.

**Comment by Elektordi** [comment] 2023-02-06 23:51
Duplicate of issue #79. @iarspider is right, the compat version should help you.
The next version of this package will support v5, but I'm still not sure when it will be released...

**Closed by Elektordi** 2023-02-06 23:51 UTC
