### ISSUE TITLE
Generic requests from python to functions in OBS 

### ISSUE THREAD

**Issue by rahulsrinivasan1** [Elektordi/obs-websocket-py#66] opened 2021-09-09 13:30 UTC
Hello.
Is it possible to build obs web sockets such that i can send requests to OBS functions directly?

**Comment by Elektordi** [comment] 2021-09-09 16:01
Duplicate of #36, yes it is planned. If needed you can create custom request class in your code. Take a look at requests.py.

**Closed by Elektordi** 2021-09-09 16:01 UTC
Labels: duplicate
