### ISSUE TITLE
I cannot change Position

### ISSUE THREAD

**Issue by menkian** [Elektordi/obs-websocket-py#42] opened 2020-08-07 22:02 UTC
Im trying to change an image position inside obs but i cant

print(ws.call(requests.GetSceneItemProperties(
    'imagen',
    scene_name='programacion'
)))

print(ws.call(requests.SetSceneItemProperties(
    'imagen',
    scene_name='programacion',
    position_x=250,
    position_y=300,
)))

print(ws.call(requests.GetSceneItemProperties(
    'imagen',
    scene_name='programacion'
)))

<GetSceneItemProperties request ({'item': 'imagen', 'scene-name': 'programacion'}) called: success ({'bounds': {'alignment': 0, 'type': 'OBS_BOUNDS_NONE', 'x': 0.0, 'y': 0.0}, 'crop': {'bottom': 0, 'left': 0, 'right': 0, 'top': 0}, 'height': 509.0, 'itemId': 11, 'locked': False, 'name': 'imagen', 'position': {'alignment': 5, 'x': 89.0, 'y': 114.0}, 'rotation': 0.0, 'scale': {'x': 1.0, 'y': 1.0}, 'sourceHeight': 509, 'sourceWidth': 1188, 'visible': True, 'width': 1188.0})>
<SetSceneItemProperties request ({'item': 'imagen', 'scene-name': 'programacion', 'position.x': 250, 'position.y': 300, 'position.alignment': None, 'rotation': None, 'scale.x': None, 'scale.y': None, 'crop.top': None, 'crop.bottom': None, 'crop.left': None, 'crop.right': None, 'visible': None, 'locked': None, 'bounds.type': None, 'bounds.alignment': None, 'bounds.x': None, 'bounds.y': None}) called: success ({})>
<GetSceneItemProperties request ({'item': 'imagen', 'scene-name': 'programacion'}) called: success ({'bounds': {'alignment': 0, 'type': 'OBS_BOUNDS_NONE', 'x': 0.0, 'y': 0.0}, 'crop': {'bottom': 0, 'left': 0, 'right': 0, 'top': 0}, 'height': 509.0, 'itemId': 11, 'locked': False, 'name': 'imagen', 'position': {'alignment': 5, 'x': 89.0, 'y': 114.0}, 'rotation': 0.0, 'scale': {'x': 1.0, 'y': 1.0}, 'sourceHeight': 509, 'sourceWidth': 1188, 'visible': True, 'width': 1188.0})>

**Comment by Elektordi** [comment] 2020-08-17 17:55
Hello,

Looks like a duplicate of issue #34 
The fix is not yet in pip, but you can try to install the new version in a venv to test. In your venv, clone the repo or use `pip3 install git+https://github.com/Elektordi/obs-websocket-py`.

If you think your problem is different, feel free to reopen the issue.

Best regards,

**Closed by Elektordi** 2020-08-17 17:55 UTC
Labels: duplicate
