### ISSUE TITLE
Do merge and update to websocket 5.0

### ISSUE THREAD

**Issue by kozaka-tv** [Elektordi/obs-websocket-py#79] opened 2023-01-30 14:24 UTC
I hope that the merges will happen soon, and this will be not a dead project...

So, please can you do the merges and update to websocket 5? Or give to some active members the rights to be able to merge. Thank you!

**Comment by alexleandrom** [comment] 2023-02-03 15:44
I buddy, I think I have the same problem, here when I try to connect I always have problema to connect, I try do debug the lib code and I finded the problem, when websocket is connect the service return this json:

`{
   "d":{
      "authentication":{
         "challenge":"+EjnsuUtmDRr69td7pMDeSceQdB7DTqoa34vYUopRsk=",
         "salt":"KS/Inuexk0Jl1as/uQhAXKO/bwl6pJwVfVao5ng1Zg8="
      },
      "obsWebSocketVersion":"5.1.0",
      "rpcVersion":1
   },
   "op":0
}`

And the lib wait for this verification 

`if result['status'] != 'ok':
            raise exceptions.ConnectionFailure(result['error'])`

I think the main problem is about websocket connect returns and how the lib wait this return.

I am using MacBook OBS Version 29 and Python 3.10.8

**Comment by Elektordi** [comment] 2023-02-06 23:52
Duplicate of issue #77 . Thanks for the debug!
The next version of this package will support v5, but I'm still not sure when it will be released...

**Closed by Elektordi** 2023-02-06 23:52 UTC
